name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:
      #скачиваем репозиторий
      - uses: actions/checkout@v3
        #настраиваем джава
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' #одна из дистрибуций
          java-version: '11'
          #запуск теста
      - run: ./gradlew clean test
